#pragma once

namespace obsidian::core {

// From SDL_keycode.h

enum class KeyCode {
  key_unknown = 0,

  ret = '\r',
  escape = '\x1B',
  backspace = '\b',
  tab = '\t',
  space = ' ',
  exclaim = '!',
  quotedbl = '"',
  hash = '#',
  percent = '%',
  dollar = '$',
  ampersand = '&',
  quote = '\'',
  leftparen = '(',
  rightparen = ')',
  asterisk = '*',
  plus = '+',
  comma = ',',
  minus = '-',
  period = '.',
  slash = '/',
  zero = '0',
  one = '1',
  two = '2',
  three = '3',
  four = '4',
  five = '5',
  six = '6',
  seven = '7',
  eight = '8',
  nine = '9',
  colon = ':',
  semicolon = ';',
  less = '<',
  equals = '=',
  greater = '>',
  question = '?',
  at = '@',

  leftbracket = '[',
  backslash = '\\',
  rightbracket = ']',
  caret = '^',
  underscore = '_',
  backquote = '`',

  a = 'a',
  b = 'b',
  c = 'c',
  d = 'd',
  e = 'e',
  f = 'f',
  g = 'g',
  h = 'h',
  i = 'i',
  j = 'j',
  k = 'k',
  l = 'l',
  m = 'm',
  n = 'n',
  o = 'o',
  p = 'p',
  q = 'q',
  r = 'r',
  s = 's',
  t = 't',
  u = 'u',
  v = 'v',
  w = 'w',
  x = 'x',
  y = 'y',
  z = 'z',

  f1 = (1 << 30) | 58,
  f2 = (1 << 30) | 59,
  f3 = (1 << 30) | 60,
  f4 = (1 << 30) | 61,
  f5 = (1 << 30) | 62,
  f6 = (1 << 30) | 63,
  f7 = (1 << 30) | 64,
  f8 = (1 << 30) | 65,
  f9 = (1 << 30) | 66,
  f10 = (1 << 30) | 67,
  f11 = (1 << 30) | 68,
  f12 = (1 << 30) | 69

};

} /*namespace obsidian::core*/
